data_doc.Rmd:
  path: dev/data_doc.Rmd
  state: active
  R: R/included-datasets.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/data_doc.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_minimal_package.Rmd:
  path: dev/flat_minimal_package.Rmd
  state: active
  R: R/download_temperatures.R
  tests: tests/testthat/test-download_temperatures.R
  vignettes: vignettes/dev_save_data.Rmd
  inflate:
    flat_file: dev/flat_minimal_package.Rmd
    vignette_name: dev_save_data
    open_vignette: false
    check: true
    document: true
    overwrite: 'yes'
